# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
   include:
     - main
     - ADODemo
 paths:
   exclude:
     - azure-pipelines.yml
     - /*.ps1

resources:
  repositories:
  - repository: eShopOnWeb
    type: github
    name: kloudsavvy7/eShopOnWeb
    ref: refs/heads/main
    endpoint: github.com_kloudsavvy7
pool:
  name: KloudsavvyDevOpsPool
  demands:
  - Agent.Name -equals DotnetBuildAgent

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo $(Build.SourcesDirectory)
  displayName: 'Run a multi-line script'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"
      $files = get-ChildItem -path C:\KloudsavvyTraining -recurse -force
      write-output "Below are the files from given path"
      write-output "$(Build.SourcesDirectory)"
